<?php 

class IASD_RegisterFields {
	public static function acf_fields(){
		acf_add_local_field_group(array (
			'key' => 'group_555c7ec2a92a0',
			'title' => __('Select Event', 'iasd'),
			'fields' => array (
				array (
					'key' => 'field_555c7ef5c0625',
					'label' => __('Event', 'iasd'),
					'name' => 'evento',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'events_cpt',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 1,
					'return_format' => 'id',
					'ui' => 1,
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'videos_cpt',
					),
				),
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'speaker_cpt',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'side',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
		));

		acf_add_local_field_group(array (
			'key' => 'group_555a2e720045f',
			'title' => __('Event Settings', 'iasd'),
			'fields' => array (
				array (
					'key' => 'field_555b6b1aa6edc',
					'label' => __('Event', 'iasd'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
				),
				array (
					'key' => 'field_555a2e72213de',
					'label' => __('Chatroll url', 'iasd'),
					'name' => 'chatroll',
					'type' => 'text',
					'instructions' => __('Coloque aqui o endereço do chat', 'iasd'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_555a2e7221402',
					'label' => __('Primary Player', 'iasd'),
					'name' => 'primary_player',
					'type' => 'textarea',
					'instructions' => __('Respect the dimensions: 
						Width: 100%
						Height: 400px', 'iasd'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_555a2ebddd29e',
					'label' => __('Secondary Player', 'iasd'),
					'name' => 'secondary_player',
					'type' => 'textarea',
					'instructions' => __('Respect the dimensions: 
						Width: 100%
						Height: 400px', 'iasd'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_557aeaf611fa7',
					'label' => __('Enable Video Gallery', 'iasd'),
					'name' => 'enable_videos',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_555ce0e67a77a',
					'label' => __('Number of Videos', 'iasd'),
					'name' => 'n_videos',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 6,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 0,
					'max' => 12,
					'step' => 3,
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_555f14599dfbb',
					'label' => __('Program', 'iasd'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
				),
				array (
					'key' => 'field_557aed5911fa8',
					'label' => __('Enable Program', 'iasd'),
					'name' => 'enable_program',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_555a315ac368c',
					'label' => __('Program', 'iasd'),
					'name' => 'schedule',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'min' => '',
					'max' => '',
					'layout' => 'row',
					'button_label' => __('Adicionar Periodo', 'iasd'),
					'sub_fields' => array (
						array (
							'key' => 'field_555a374cc368d',
							'label' => __('Period', 'iasd'),
							'name' => 'period',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 100,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_555cdc984793d',
							'label' => __('Activar', 'iasd'),
							'name' => 'enable',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
						),
						array (
							'key' => 'field_555a387c24b18',
							'label' => __('Event', 'iasd'),
							'name' => 'event',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => __('Adicionar Evento', 'iasd'),
							'sub_fields' => array (
								array (
									'key' => 'field_555a388d24b19',
									'label' => __('Event', 'iasd'),
									'name' => 'event',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 70,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_555a38a624b1a',
									'label' => __('Time', 'iasd'),
									'name' => 'time',
									'type' => 'text',
									'instructions' => __('Format: hh:mm', 'iasd'),
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 30,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
				),
				array (
					'key' => 'field_555b6adca6edb',
					'label' => __('Design', 'iasd'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
				),
				array (
					'key' => 'field_555b85ba39329',
					'label' => __('Hight Contrast', 'iasd'),
					'name' => 'contrast',
					'type' => 'true_false',
					'instructions' => __('If true, the text of the header and footer will be dark.', 'iasd'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_555a2f0cdd29f',
					'label' => __('Imagen de cabecera', 'iasd'),
					'name' => 'header_image',
					'type' => 'image',
					'instructions' => __('Image dimensions:
						min-width: 1920px
						min-height: 225px', 'iasd'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'uploadedTo',
					'min_width' => 1920,
					'min_height' => 225,
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_555a2fa7dd2a0',
					'label' => __('Footer Image', 'iasd'),
					'name' => 'footer_image',
					'type' => 'image',
					'instructions' => __('Image dimensions: 
						min-width: 1920px
						min-height: 700px', 'iasd'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => 1920,
					'min_height' => 700,
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_555b5459c70db',
					'label' => __('Custom CSS', 'iasd'),
					'name' => 'css',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'events_cpt',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'comments',
				4 => 'revisions',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		));
	}
}

add_action( 'after_setup_theme', array('IASD_RegisterFields', 'acf_fields'), 0 );

