<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_581b7da84d85b',
	'title' => 'Página Especial',
	'fields' => array (
		array (
			'key' => 'field_581b8996c7779',
			'label' => 'Conteúdo',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_581b9b024c5d2',
			'label' => 'Título',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_581b9b114c5d3',
			'label' => 'Subtítulo',
			'name' => 'subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_581b7daed0531',
			'label' => 'Sessões',
			'name' => 'special_flex_content',
			'type' => 'flexible_content',
			'instructions' => 'Adicione e reposicione as sessões clicando e arrastando',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Adicionar sessão',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '581b7f21d0538',
					'name' => 'content_video',
					'label' => 'Vídeo',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_581b84ab9dae8',
							'label' => 'Contéudo',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'field_581b7f8ed053a',
							'label' => 'Fonte',
							'name' => 'source',
							'type' => 'oembed',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'width' => '',
							'height' => '',
						),
						array (
							'key' => 'field_581b7f59d0539',
							'label' => 'Layout',
							'name' => 'layout',
							'type' => 'select',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'full' => 'Largura do monitor',
								'fit' => 'Largura da página',
							),
							'default_value' => array (
							),
							'allow_null' => '',
							'multiple' => '',
							'ui' => '',
							'ajax' => '',
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_581b7faad053b',
							'label' => 'Tamanho',
							'name' => 'size',
							'type' => 'select',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'16by9' => '16:9',
								'4by3' => '4:3',
							),
							'default_value' => array (
								0 => '16by9',
							),
							'allow_null' => '',
							'multiple' => '',
							'ui' => '',
							'ajax' => '',
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_581b8023d053c',
							'label' => 'Legenda',
							'name' => 'legend',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 3,
							'new_lines' => 'br',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_581b84b59dae9',
							'label' => 'Design',
							'name' => '_copiar',
							'type' => 'tab',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'field_581b84cd9daea',
							'label' => 'Cor de fundo',
							'name' => 'bg_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array (
							'key' => 'field_581b84e09daeb',
							'label' => 'Cor do texto',
							'name' => 'text_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '581b8398d053e',
					'name' => 'content_image',
					'label' => 'Imagem',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_581b8398d053f',
							'label' => 'Layout',
							'name' => 'layout',
							'type' => 'select',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'full' => 'Largura do monitor',
								'fit' => 'Largura da página',
							),
							'default_value' => array (
							),
							'allow_null' => '',
							'multiple' => '',
							'ui' => '',
							'ajax' => '',
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_581b8398d0540',
							'label' => 'Arquivo',
							'name' => 'source',
							'type' => 'image',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => '',
							'preview_size' => 'thumbnail',
							'library' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_581b8398d0542',
							'label' => 'Legenda',
							'name' => 'legend',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'visual',
							'toolbar' => 'basic',
							'media_upload' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '581b83ecd0543',
					'name' => 'content_posts',
					'label' => 'Artigos',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_581b8458d054a',
							'label' => 'Conteúdo',
							'name' => '_copiar',
							'type' => 'tab',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'field_581b8404d0544',
							'label' => 'Título',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_581b8414d0546',
							'label' => 'Descrição',
							'name' => 'description',
							'type' => 'text',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_581b846cd054b',
							'label' => 'Posts',
							'name' => 'posts',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Adicionar Post',
							'sub_fields' => array (
								array (
									'key' => 'field_581c7fe1cfe88',
									'label' => 'Thumb',
									'name' => 'thumbnail',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_581c7ff7cfe89',
									'label' => 'Título',
									'name' => 'title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_581c8002cfe8a',
									'label' => 'Link',
									'name' => 'link',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
							),
						),
						array (
							'key' => 'field_581b8442d0549',
							'label' => 'Design',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'field_581b841cd0547',
							'label' => 'Cor de fundo',
							'name' => 'bg_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array (
							'key' => 'field_581b8428d0548',
							'label' => 'Cor de texto',
							'name' => 'text_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '581b8744d9a4b',
					'name' => 'content_text',
					'label' => 'Texto',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_581b8744d9a4c',
							'label' => 'Conteúdo',
							'name' => '_copiar',
							'type' => 'tab',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => '',
						),
						array (
							'key' => 'field_581b8744d9a4d',
							'label' => 'Título',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_581b8744d9a4e',
							'label' => 'Descrição',
							'name' => 'description',
							'type' => 'text',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_581b8744d9a4f',
							'label' => 'Editor',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
						),
						array (
							'key' => 'field_581b8744d9a51',
							'label' => 'Design',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => '',
						),
						array (
							'key' => 'field_581b8744d9a52',
							'label' => 'Cor de fundo',
							'name' => 'bg_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array (
							'key' => 'field_581b876fd9a54',
							'label' => 'Imagem de fundo',
							'name' => 'bg_image',
							'type' => 'image',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_581b8786d9a55',
							'label' => 'Vídeo de fundo',
							'name' => 'bg_video',
							'type' => 'text',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_581b8744d9a53',
							'label' => 'Cor de texto',
							'name' => 'text_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '581b7e9dd0534',
					'name' => 'content_footer',
					'label' => 'Créditos',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_581b7ec1d0535',
							'label' => 'Créditos',
							'name' => 'credits',
							'type' => 'repeater',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => '',
							'button_label' => 'Adicionar Crédito',
							'sub_fields' => array (
								array (
									'key' => 'field_581b7eead0536',
									'label' => 'Descrição',
									'name' => 'description',
									'type' => 'text',
									'instructions' => '',
									'required' => '',
									'conditional_logic' => '',
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_581b7f03d0537',
									'label' => 'Nomes',
									'name' => 'names',
									'type' => 'text',
									'instructions' => '',
									'required' => '',
									'conditional_logic' => '',
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '581b840bd0545',
					'name' => 'content_sidebar',
					'label' => 'Área de widgets',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_581b8719d9a49',
							'label' => 'Sidebar',
							'name' => 'sidebar',
							'type' => 'sidebar_selector',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'allow_null' => 1,
							'default_value' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
		array (
			'key' => 'field_581b89a5c777a',
			'label' => 'Design',
			'name' => 'design',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_581b89b0c777b',
			'label' => 'Imagem de fundo',
			'name' => 'bg_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_581b89c2c777c',
			'label' => 'Cor de fundo',
			'name' => 'bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_581b89ddc777d',
			'label' => 'Cor para texto',
			'name' => 'text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_581b8ea99864d',
			'label' => 'Imagem de fundo do rodapé',
			'name' => 'bg_image_footer',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-special-page.php',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-custom-page.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

endif;